version: '3'
name: php-nginx-xdebug
services:
  webserver:
    image: nginx:1.25
    ports:
      - 8002:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build: ./.docker/php/
    volumes:
      - ./src:/usr/share/nginx/html
      - ./.docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/config/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
   
